<a href="https://colab.research.google.com/github/HarideP/digilent-xdc/blob/master/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(size=(7, 7))
tensor_A

tensor([[0.3451, 0.6123, 0.5047, 0.0652, 0.3627, 0.9509, 0.0949],
        [0.5144, 0.4881, 0.8069, 0.5151, 0.8897, 0.2066, 0.4337],
        [0.2968, 0.9259, 0.7419, 0.8906, 0.5691, 0.6310, 0.2476],
        [0.5584, 0.8275, 0.9466, 0.0961, 0.9125, 0.5627, 0.3715],
        [0.3864, 0.3213, 0.9396, 0.5599, 0.4380, 0.0950, 0.1621],
        [0.1746, 0.7831, 0.4908, 0.4147, 0.8582, 0.3290, 0.1447],
        [0.1458, 0.5564, 0.3271, 0.0788, 0.3408, 0.8189, 0.0825]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor_B = torch.rand(size=(1, 7))
print(tensor_B)
# Perform matrix multiplication
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

tensor([[0.1238, 0.0775, 0.7039, 0.1930, 0.3819, 0.4805, 0.3638]])
tensor([[1.0880],
        [1.3658],
        [1.4133],
        [1.5722],
        [1.1141],
        [1.0464],
        [0.8603]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors

tensor_C = torch.rand(7, 7)

tensor_D = torch.rand(1, 7)


# Matrix multiply tensors
output = torch.matmul(tensor_C, tensor_D.T)
print(output)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [23]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cpu" if torch.cuda.is_available()==False else "cuda"
print(device)

# Create two random tensors on GPU
tensor_E = torch.rand(size=(2, 3)).to(device)
tensor_F = torch.rand(size=(2, 3)).to(device)
print(tensor_E)
print(tensor_F)

cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [34]:
# Perform matmul on tensor_A and tensor_B
output7 = torch.matmul(tensor_E, tensor_F.T)
print(output7)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [36]:
# Find max
max_in_output7 = torch.max(output7)
print(max_in_output7)
# Find min
min_in_output7 = torch.min(output7)
print(min_in_output7)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [38]:
# Find arg max
print(torch.argmax(output7))

# Find arg min
print(torch.argmin(output7))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [39]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_G = torch.rand(size=(1, 1, 1, 10))


# Remove single dimensions
tensor = tensor_G.squeeze()

# Print out tensors and their shapes
print(tensor), print(tensor.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])


(None, None)